<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAkJE00H\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAkJE00H/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAkJE00H.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAkJE00H\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAkJE00H\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AkJE00H',
    'container.build_id' => 'e671e7bc',
    'container.build_time' => 1551555456,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAkJE00H');
