version: "3.4"

services:
  php:
    image: ${DOCKER_REGISTRY}/infection-playground-php:latest
    depends_on:
      - db
    secrets:
      - mysql_password
    networks:
      - db
      - php
    environment:
      - APP_ENV=prod
      - APP_SECRET=${APP_SECRET}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD_FILE=/run/secrets/mysql_password

  web:
    image: ${DOCKER_REGISTRY}/infection-playground-nginx:latest
    depends_on:
      - php
    networks:
      - php

  db:
    image: mysql:5.7
    secrets:
      - mysql_root_password
      - mysql_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
    networks:
      - db

secrets:
  mysql_root_password:
    file: secrets/mysql_root_password
  mysql_password:
    file: secrets/mysql_password

networks:
  db:
  php:
