version: "3.4"

services:
  php:
    build:
      context: .
      target: prod
    depends_on:
       - db
    networks:
       - db
       - php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}

  nodejs:
    build:
      context: .
      target: infection_nodejs
    image: infection-nodejs:latest
    depends_on:
      - php
    networks:
      - db
      - php
    environment:
      - PHP_HOST=php
      - PHP_PORT=9000
    volumes:
      - ./app:/srv/app:rw,cached
      - ./app/public:/srv/app/public:rw,delegated
    ports:
      - "35729:35729"


  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - php
    networks:
      - php
    volumes:
      # todo move to dockerfile and skip volume? both lines
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./app/public:/app/public

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - db

networks:
  db:
  php:
