version: "3.4"

services:
  php:
    build:
      context: .
      target: prod
#    depends_on:
      # - db
  nginx:
    image: nginx:1.15-alpine
    volumes:
      # todo move to dockerfile and skip volume? both lines
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./app/public:/app/public