version: "3.9"

services:
  php:
    build:
      context: .
      target: prod
    image: ${DOCKER_REGISTRY}/infection-playground-php:latest
    depends_on:
      - db
    networks:
      - db
      - php
    environment:
      - APP_ENV=prod
      - APP_SECRET=${APP_SECRET}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  web:
    build:
      context: .
      target: infection_nginx_prod
    image: ${DOCKER_REGISTRY}/infection-playground-nginx:latest
    ports:
      - "8099:80"
    depends_on:
      - php
    networks:
      - php

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - db

networks:
  db:
  php:
