version: "3.9"

services:
  php:
    build:
      context: .
      target: prod
    depends_on:
       - db
    networks:
       - db
       - php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  nodejs:
    build:
      context: .
      target: infection_nodejs
    image: infection-nodejs:latest
    depends_on:
      - php
    networks:
      - db
      - php
    environment:
      - PHP_HOST=php
      - PHP_PORT=9000
    volumes:
      - ./app:/srv/app:rw,cached
      - ./app/public:/srv/app/public:rw,delegated
    ports:
      - "35729:35729"


  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - php
    networks:
      - php
    volumes:
      # todo move to dockerfile and skip volume? both lines
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./app/public:/app/public
    ports:
      - "8098:80"

  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - db
    ports:
      - "3354:3306"

networks:
  db:
  php:
